FROM ubi8/ubi

ENV YQ_VERSION=v4.23.1
ENV YQ_BINARY=yq_linux_amd64

USER root
RUN dnf install -y git wget python39
RUN wget https://github.com/mikefarah/yq/releases/download/${YQ_VERSION}/${YQ_BINARY}.tar.gz -O - |\
    tar xz && mv ${YQ_BINARY} /usr/bin/yq
USER 1001
