apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: yq-git
spec:
  workspaces:
    - name: clone
  params:
    - name: git-password
      description: The password to authenticate with the git repository, if using HTTPS and basic authentication.
      default: ''
      type: string
    - name: new-value
      description: Set this value at the specified path in the target file
      type: string
  steps:
    - name: yq-git
      image: quay.io/dwinchell_redhat/yq-git-ubi8:latest
      workingDir: /workspace/clone
      env:
        - name: GIT_PASSWORD
          value: $(params.git-password)
        - name: NEW_VALUE
          value: $(params.new-value)
      script: |
        #!/usr/bin/python3
        ### BUILD SCRIPT WILL INSERT CODE HERE ###
