apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  generateName: test-yq-git-
spec:
  taskRef:
    name: yq-git
  params:
    - name: git-password
      value: 
    - name: new-value
      value: newvalue1
  workspaces:
    - name: clone
      emptyDir: {}
